package com.independentsoft.exchange;

import java.util.*;

public class ItemPropertyPath
{
    public static final UnindexedPropertyPath ITEM_ID;
    public static final UnindexedPropertyPath PARENT_ID;
    public static final UnindexedPropertyPath ITEM_CLASS;
    public static final UnindexedPropertyPath SUBJECT;
    public static final UnindexedPropertyPath MIME_CONTENT;
    public static final UnindexedPropertyPath SENSITIVITY;
    public static final UnindexedPropertyPath BODY;
    public static final UnindexedPropertyPath ATTACHMENTS;
    public static final UnindexedPropertyPath SIZE;
    public static final UnindexedPropertyPath CATEGORIES;
    public static final UnindexedPropertyPath IMPORTANCE;
    public static final UnindexedPropertyPath CREATED_TIME;
    public static final UnindexedPropertyPath HAS_ATTACHMENTS;
    public static final UnindexedPropertyPath CULTURE;
    public static final UnindexedPropertyPath EFFECTIVE_RIGHTS;
    public static final UnindexedPropertyPath LAST_MODIFIER_NAME;
    public static final UnindexedPropertyPath LAST_MODIFIED_TIME;
    public static final PropertyTag DISPLAY_NAME;
    public static final PropertyTag ENTRY_ID;
    public static final PropertyTag SEARCH_KEY;
    public static final PropertyTag BODY_HTML_TEXT;
    public static final PropertyTag BODY_PLAIN_TEXT;
    public static final PropertyTag IS_HIDDEN;
    public static final UnindexedPropertyPath IS_ASSOCIATED;
    public static final UnindexedPropertyPath WEB_CLIENT_READ_FORM_QUERY_STRING;
    public static final UnindexedPropertyPath WEB_CLIENT_EDIT_FORM_QUERY_STRING;
    public static final UnindexedPropertyPath CONVERSATION_ID;
    public static final UnindexedPropertyPath UNIQUE_BODY;
    public static final UnindexedPropertyPath STORE_ENTRY_ID;
    public static final PropertyTag COMMENT;
    public static final UnindexedPropertyPath REMINDER_DUE_BY;
    public static final UnindexedPropertyPath REMINDER_IS_SET;
    public static final UnindexedPropertyPath REMINDER_MINUTES_BEFORE_START;
    public static final UnindexedPropertyPath FLAG;
    public static final UnindexedPropertyPath INSTANCE_KEY;
    public static final UnindexedPropertyPath RETENTION_TAG;
    public static final UnindexedPropertyPath ARCHIVE_TAG;
    public static final UnindexedPropertyPath RETENTION_DATE;
    public static final UnindexedPropertyPath PREVIEW;
    public static final UnindexedPropertyPath NEXT_PREDICTED_ACTION;
    public static final UnindexedPropertyPath GROUPING_ACTION;
    public static final UnindexedPropertyPath BLOCK_STATUS;
    public static final UnindexedPropertyPath HAS_BLOCKED_IMAGES;
    public static final UnindexedPropertyPath TEXT_BODY;
    public static final UnindexedPropertyPath ICON_INDEX;
    public static final UnindexedPropertyPath ENTITY_EXTRACTION_RESULT;
    
    public static List<PropertyPath> getAllPropertyPaths() {
        final ArrayList<PropertyPath> list;
        (list = new ArrayList<PropertyPath>()).add(ItemPropertyPath.ITEM_ID);
        list.add(ItemPropertyPath.PARENT_ID);
        list.add(ItemPropertyPath.ITEM_CLASS);
        list.add(ItemPropertyPath.SUBJECT);
        list.add(ItemPropertyPath.SENSITIVITY);
        list.add(ItemPropertyPath.BODY);
        list.add(ItemPropertyPath.ATTACHMENTS);
        list.add(ItemPropertyPath.SIZE);
        list.add(ItemPropertyPath.CATEGORIES);
        list.add(ItemPropertyPath.IMPORTANCE);
        list.add(ItemPropertyPath.CREATED_TIME);
        list.add(ItemPropertyPath.HAS_ATTACHMENTS);
        list.add(ItemPropertyPath.CULTURE);
        list.add(ItemPropertyPath.EFFECTIVE_RIGHTS);
        list.add(ItemPropertyPath.DISPLAY_NAME);
        list.add(ItemPropertyPath.ENTRY_ID);
        list.add(ItemPropertyPath.LAST_MODIFIER_NAME);
        list.add(ItemPropertyPath.LAST_MODIFIED_TIME);
        list.add(ItemPropertyPath.SEARCH_KEY);
        list.add(ItemPropertyPath.BODY_PLAIN_TEXT);
        list.add(ItemPropertyPath.IS_ASSOCIATED);
        list.add(ItemPropertyPath.WEB_CLIENT_READ_FORM_QUERY_STRING);
        list.add(ItemPropertyPath.WEB_CLIENT_EDIT_FORM_QUERY_STRING);
        list.add(ItemPropertyPath.CONVERSATION_ID);
        list.add(ItemPropertyPath.UNIQUE_BODY);
        list.add(ItemPropertyPath.STORE_ENTRY_ID);
        list.add(ItemPropertyPath.COMMENT);
        list.add(ItemPropertyPath.FLAG);
        list.add(ItemPropertyPath.INSTANCE_KEY);
        list.add(ItemPropertyPath.RETENTION_TAG);
        list.add(ItemPropertyPath.ARCHIVE_TAG);
        list.add(ItemPropertyPath.RETENTION_DATE);
        list.add(ItemPropertyPath.PREVIEW);
        list.add(ItemPropertyPath.NEXT_PREDICTED_ACTION);
        list.add(ItemPropertyPath.GROUPING_ACTION);
        list.add(ItemPropertyPath.BLOCK_STATUS);
        list.add(ItemPropertyPath.HAS_BLOCKED_IMAGES);
        list.add(ItemPropertyPath.TEXT_BODY);
        list.add(ItemPropertyPath.ICON_INDEX);
        return (List<PropertyPath>)list;
    }
    
    static {
        ITEM_ID = new UnindexedPropertyPath("item:ItemId");
        PARENT_ID = new UnindexedPropertyPath("item:ParentFolderId");
        ITEM_CLASS = new UnindexedPropertyPath("item:ItemClass");
        SUBJECT = new UnindexedPropertyPath("item:Subject");
        MIME_CONTENT = new UnindexedPropertyPath("item:MimeContent");
        SENSITIVITY = new UnindexedPropertyPath("item:Sensitivity");
        BODY = new UnindexedPropertyPath("item:Body");
        ATTACHMENTS = new UnindexedPropertyPath("item:Attachments");
        SIZE = new UnindexedPropertyPath("item:Size");
        CATEGORIES = new UnindexedPropertyPath("item:Categories");
        IMPORTANCE = new UnindexedPropertyPath("item:Importance");
        CREATED_TIME = new UnindexedPropertyPath("item:DateTimeCreated");
        HAS_ATTACHMENTS = new UnindexedPropertyPath("item:HasAttachments");
        CULTURE = new UnindexedPropertyPath("item:Culture");
        EFFECTIVE_RIGHTS = new UnindexedPropertyPath("item:EffectiveRights");
        LAST_MODIFIER_NAME = new UnindexedPropertyPath("item:LastModifiedName");
        LAST_MODIFIED_TIME = new UnindexedPropertyPath("item:LastModifiedTime");
        DISPLAY_NAME = MapiPropertyTag.PR_DISPLAY_NAME;
        ENTRY_ID = MapiPropertyTag.PR_ENTRYID;
        SEARCH_KEY = MapiPropertyTag.PR_SEARCH_KEY;
        BODY_HTML_TEXT = MapiPropertyTag.PR_HTML;
        BODY_PLAIN_TEXT = MapiPropertyTag.PR_BODY;
        IS_HIDDEN = MapiPropertyTag.PR_ATTR_HIDDEN;
        IS_ASSOCIATED = new UnindexedPropertyPath("item:IsAssociated");
        WEB_CLIENT_READ_FORM_QUERY_STRING = new UnindexedPropertyPath("item:WebClientReadFormQueryString");
        WEB_CLIENT_EDIT_FORM_QUERY_STRING = new UnindexedPropertyPath("item:WebClientEditFormQueryString");
        CONVERSATION_ID = new UnindexedPropertyPath("item:ConversationId");
        UNIQUE_BODY = new UnindexedPropertyPath("item:UniqueBody");
        STORE_ENTRY_ID = new UnindexedPropertyPath("item:StoreEntryId");
        COMMENT = MapiPropertyTag.PR_COMMENT;
        REMINDER_DUE_BY = new UnindexedPropertyPath("item:ReminderDueBy");
        REMINDER_IS_SET = new UnindexedPropertyPath("item:ReminderIsSet");
        REMINDER_MINUTES_BEFORE_START = new UnindexedPropertyPath("item:ReminderMinutesBeforeStart");
        FLAG = new UnindexedPropertyPath("item:Flag");
        INSTANCE_KEY = new UnindexedPropertyPath("item:InstanceKey");
        RETENTION_TAG = new UnindexedPropertyPath("item:PolicyTag");
        ARCHIVE_TAG = new UnindexedPropertyPath("item:ArchiveTag");
        RETENTION_DATE = new UnindexedPropertyPath("item:RetentionDate");
        PREVIEW = new UnindexedPropertyPath("item:Preview");
        NEXT_PREDICTED_ACTION = new UnindexedPropertyPath("item:NextPredictedAction");
        GROUPING_ACTION = new UnindexedPropertyPath("item:GroupingAction");
        BLOCK_STATUS = new UnindexedPropertyPath("item:BlockStatus");
        HAS_BLOCKED_IMAGES = new UnindexedPropertyPath("item:HasBlockedImages");
        TEXT_BODY = new UnindexedPropertyPath("item:TextBody");
        ICON_INDEX = new UnindexedPropertyPath("item:IconIndex");
        ENTITY_EXTRACTION_RESULT = new UnindexedPropertyPath("item:EntityExtractionResult");
    }
}
