package com.ews.exchange;

import java.util.*;

public class PersonaPropertyPath
{
    public static final UnindexedPropertyPath PERSONA_ID;
    public static final UnindexedPropertyPath PERSONA_TYPE;
    public static final UnindexedPropertyPath PERSONA_OBJECT_STATUS;
    public static final UnindexedPropertyPath CREATION_TIME;
    public static final UnindexedPropertyPath DISPLAY_NAME;
    public static final UnindexedPropertyPath FILE_AS;
    public static final UnindexedPropertyPath FILE_AS_ID;
    public static final UnindexedPropertyPath DISPLAY_NAME_PREFIX;
    public static final UnindexedPropertyPath GIVEN_NAME;
    public static final UnindexedPropertyPath MIDDLE_NAME;
    public static final UnindexedPropertyPath SURNAME;
    public static final UnindexedPropertyPath GENERATION;
    public static final UnindexedPropertyPath NICKNAME;
    public static final UnindexedPropertyPath YOMI_COMPANY_NAME;
    public static final UnindexedPropertyPath YOMI_FIRST_NAME;
    public static final UnindexedPropertyPath YOMI_LAST_NAME;
    public static final UnindexedPropertyPath TITLE;
    public static final UnindexedPropertyPath DEPARTMENT;
    public static final UnindexedPropertyPath COMPANY_NAME;
    public static final UnindexedPropertyPath EMAIL_ADDRESS;
    public static final UnindexedPropertyPath EMAIL_ADDRESSES;
    public static final UnindexedPropertyPath PHONE_NUMBER;
    public static final UnindexedPropertyPath IM_ADDRESS;
    public static final UnindexedPropertyPath HOME_CITY;
    public static final UnindexedPropertyPath WORK_CITY;
    public static final UnindexedPropertyPath RELEVANCE_SCORE;
    public static final UnindexedPropertyPath FOLDER_IDS;
    public static final UnindexedPropertyPath ATTRIBUTIONS;
    public static final UnindexedPropertyPath DISPLAY_NAMES;
    public static final UnindexedPropertyPath FILE_ASES;
    public static final UnindexedPropertyPath FILE_AS_IDS;
    public static final UnindexedPropertyPath DISPLAY_NAME_PREFIXES;
    public static final UnindexedPropertyPath GIVEN_NAMES;
    public static final UnindexedPropertyPath MIDDLE_NAMES;
    public static final UnindexedPropertyPath SURNAMES;
    public static final UnindexedPropertyPath GENERATIONS;
    public static final UnindexedPropertyPath NICKNAMES;
    public static final UnindexedPropertyPath INITIALS;
    public static final UnindexedPropertyPath YOMI_COMPANY_NAMES;
    public static final UnindexedPropertyPath YOMI_FIRST_NAMES;
    public static final UnindexedPropertyPath YOMI_LAST_NAMES;
    public static final UnindexedPropertyPath BUSINESS_PHONE_NUMBERS;
    public static final UnindexedPropertyPath BUSINESS_PHONE_NUMBERS_2;
    public static final UnindexedPropertyPath HOME_PHONES;
    public static final UnindexedPropertyPath HOME_PHONES_2;
    public static final UnindexedPropertyPath MOBILE_PHONES;
    public static final UnindexedPropertyPath MOBILE_PHONES_2;
    public static final UnindexedPropertyPath ASSISTANT_PHONE_NUMBERS;
    public static final UnindexedPropertyPath CALLBACK_PHONES;
    public static final UnindexedPropertyPath CAR_PHONES;
    public static final UnindexedPropertyPath HOME_FAXES;
    public static final UnindexedPropertyPath ORGANIZATION_MAIN_PHONES;
    public static final UnindexedPropertyPath OTHER_FAXES;
    public static final UnindexedPropertyPath OTHER_TELEPHONES;
    public static final UnindexedPropertyPath OTHER_PHONES_2;
    public static final UnindexedPropertyPath PAGERS;
    public static final UnindexedPropertyPath RADIO_PHONES;
    public static final UnindexedPropertyPath TELEX_NUMBERS;
    public static final UnindexedPropertyPath WORK_FAXES;
    public static final UnindexedPropertyPath EMAILS_1;
    public static final UnindexedPropertyPath EMAILS_2;
    public static final UnindexedPropertyPath EMAILS_3;
    public static final UnindexedPropertyPath BUSINESS_HOME_PAGES;
    public static final UnindexedPropertyPath PERSONAL_HOME_PAGES;
    public static final UnindexedPropertyPath OFFICE_LOCATIONS;
    public static final UnindexedPropertyPath IM_ADDRESSES;
    public static final UnindexedPropertyPath IM_ADDRESSES_2;
    public static final UnindexedPropertyPath IM_ADDRESSES_3;
    public static final UnindexedPropertyPath BUSINESS_ADDRESSES;
    public static final UnindexedPropertyPath HOME_ADDRESSES;
    public static final UnindexedPropertyPath OTHER_ADDRESSES;
    public static final UnindexedPropertyPath TITLES;
    public static final UnindexedPropertyPath DEPARTMENTS;
    public static final UnindexedPropertyPath COMPANY_NAMES;
    public static final UnindexedPropertyPath MANAGERS;
    public static final UnindexedPropertyPath ASSISTANT_NAMES;
    public static final UnindexedPropertyPath PROFESSIONS;
    public static final UnindexedPropertyPath SPOUSE_NAMES;
    public static final UnindexedPropertyPath CHILDREN;
    public static final UnindexedPropertyPath SCHOOLS;
    public static final UnindexedPropertyPath HOBBIES;
    public static final UnindexedPropertyPath WEDDING_ANNIVERSARIES;
    public static final UnindexedPropertyPath BIRTHDAYS;
    public static final UnindexedPropertyPath LOCATIONS;
    public static final UnindexedPropertyPath EXTENDED_PROPERTIES;
    
    public static List<PropertyPath> getAllPropertyPaths() {
        final ArrayList<PropertyPath> list = new ArrayList<PropertyPath>();
        for (int i = 0; i < ItemPropertyPath.getAllPropertyPaths().size(); ++i) {
            list.add((PropertyPath)ItemPropertyPath.getAllPropertyPaths().get(i));
        }
        list.add(PersonaPropertyPath.PERSONA_ID);
        list.add(PersonaPropertyPath.PERSONA_TYPE);
        list.add(PersonaPropertyPath.PERSONA_OBJECT_STATUS);
        list.add(PersonaPropertyPath.CREATION_TIME);
        list.add(PersonaPropertyPath.DISPLAY_NAME);
        list.add(PersonaPropertyPath.FILE_AS);
        list.add(PersonaPropertyPath.FILE_AS_ID);
        list.add(PersonaPropertyPath.DISPLAY_NAME_PREFIX);
        list.add(PersonaPropertyPath.GIVEN_NAME);
        list.add(PersonaPropertyPath.MIDDLE_NAME);
        list.add(PersonaPropertyPath.SURNAME);
        list.add(PersonaPropertyPath.GENERATION);
        list.add(PersonaPropertyPath.NICKNAME);
        list.add(PersonaPropertyPath.YOMI_COMPANY_NAME);
        list.add(PersonaPropertyPath.YOMI_FIRST_NAME);
        list.add(PersonaPropertyPath.YOMI_LAST_NAME);
        list.add(PersonaPropertyPath.TITLE);
        list.add(PersonaPropertyPath.DEPARTMENT);
        list.add(PersonaPropertyPath.COMPANY_NAME);
        list.add(PersonaPropertyPath.EMAIL_ADDRESS);
        list.add(PersonaPropertyPath.EMAIL_ADDRESSES);
        list.add(PersonaPropertyPath.PHONE_NUMBER);
        list.add(PersonaPropertyPath.IM_ADDRESS);
        list.add(PersonaPropertyPath.HOME_CITY);
        list.add(PersonaPropertyPath.WORK_CITY);
        list.add(PersonaPropertyPath.RELEVANCE_SCORE);
        list.add(PersonaPropertyPath.FOLDER_IDS);
        list.add(PersonaPropertyPath.ATTRIBUTIONS);
        list.add(PersonaPropertyPath.DISPLAY_NAMES);
        list.add(PersonaPropertyPath.FILE_ASES);
        list.add(PersonaPropertyPath.FILE_AS_IDS);
        list.add(PersonaPropertyPath.DISPLAY_NAME_PREFIXES);
        list.add(PersonaPropertyPath.GIVEN_NAMES);
        list.add(PersonaPropertyPath.MIDDLE_NAMES);
        list.add(PersonaPropertyPath.SURNAMES);
        list.add(PersonaPropertyPath.GENERATIONS);
        list.add(PersonaPropertyPath.NICKNAMES);
        list.add(PersonaPropertyPath.INITIALS);
        list.add(PersonaPropertyPath.YOMI_COMPANY_NAMES);
        list.add(PersonaPropertyPath.YOMI_FIRST_NAMES);
        list.add(PersonaPropertyPath.YOMI_LAST_NAMES);
        list.add(PersonaPropertyPath.BUSINESS_PHONE_NUMBERS);
        list.add(PersonaPropertyPath.BUSINESS_PHONE_NUMBERS_2);
        list.add(PersonaPropertyPath.HOME_PHONES);
        list.add(PersonaPropertyPath.HOME_PHONES_2);
        list.add(PersonaPropertyPath.MOBILE_PHONES);
        list.add(PersonaPropertyPath.MOBILE_PHONES_2);
        list.add(PersonaPropertyPath.ASSISTANT_PHONE_NUMBERS);
        list.add(PersonaPropertyPath.CALLBACK_PHONES);
        list.add(PersonaPropertyPath.CAR_PHONES);
        list.add(PersonaPropertyPath.HOME_FAXES);
        list.add(PersonaPropertyPath.ORGANIZATION_MAIN_PHONES);
        list.add(PersonaPropertyPath.OTHER_FAXES);
        list.add(PersonaPropertyPath.OTHER_TELEPHONES);
        list.add(PersonaPropertyPath.OTHER_PHONES_2);
        list.add(PersonaPropertyPath.PAGERS);
        list.add(PersonaPropertyPath.RADIO_PHONES);
        list.add(PersonaPropertyPath.TELEX_NUMBERS);
        list.add(PersonaPropertyPath.WORK_FAXES);
        list.add(PersonaPropertyPath.EMAILS_1);
        list.add(PersonaPropertyPath.EMAILS_2);
        list.add(PersonaPropertyPath.EMAILS_3);
        list.add(PersonaPropertyPath.BUSINESS_HOME_PAGES);
        list.add(PersonaPropertyPath.PERSONAL_HOME_PAGES);
        list.add(PersonaPropertyPath.OFFICE_LOCATIONS);
        list.add(PersonaPropertyPath.IM_ADDRESSES);
        list.add(PersonaPropertyPath.IM_ADDRESSES_2);
        list.add(PersonaPropertyPath.IM_ADDRESSES_3);
        list.add(PersonaPropertyPath.BUSINESS_ADDRESSES);
        list.add(PersonaPropertyPath.HOME_ADDRESSES);
        list.add(PersonaPropertyPath.OTHER_ADDRESSES);
        list.add(PersonaPropertyPath.TITLES);
        list.add(PersonaPropertyPath.DEPARTMENTS);
        list.add(PersonaPropertyPath.COMPANY_NAMES);
        list.add(PersonaPropertyPath.MANAGERS);
        list.add(PersonaPropertyPath.ASSISTANT_NAMES);
        list.add(PersonaPropertyPath.PROFESSIONS);
        list.add(PersonaPropertyPath.SPOUSE_NAMES);
        list.add(PersonaPropertyPath.CHILDREN);
        list.add(PersonaPropertyPath.SCHOOLS);
        list.add(PersonaPropertyPath.HOBBIES);
        list.add(PersonaPropertyPath.WEDDING_ANNIVERSARIES);
        list.add(PersonaPropertyPath.BIRTHDAYS);
        list.add(PersonaPropertyPath.LOCATIONS);
        list.add(PersonaPropertyPath.EXTENDED_PROPERTIES);
        return (List<PropertyPath>)list;
    }
    
    static {
        PERSONA_ID = new UnindexedPropertyPath("persona:PersonaId");
        PERSONA_TYPE = new UnindexedPropertyPath("persona:PersonaType");
        PERSONA_OBJECT_STATUS = new UnindexedPropertyPath("persona:PersonaObjectStatus");
        CREATION_TIME = new UnindexedPropertyPath("persona:CreationTime");
        DISPLAY_NAME = new UnindexedPropertyPath("persona:DisplayName");
        FILE_AS = new UnindexedPropertyPath("persona:FileAs");
        FILE_AS_ID = new UnindexedPropertyPath("persona:FileAsId");
        DISPLAY_NAME_PREFIX = new UnindexedPropertyPath("persona:DisplayNamePrefix");
        GIVEN_NAME = new UnindexedPropertyPath("persona:GivenName");
        MIDDLE_NAME = new UnindexedPropertyPath("contacts:MiddleName");
        SURNAME = new UnindexedPropertyPath("persona:Surname");
        GENERATION = new UnindexedPropertyPath("contacts:Generation");
        NICKNAME = new UnindexedPropertyPath("contacts:Nickname");
        YOMI_COMPANY_NAME = new UnindexedPropertyPath("persona:YomiCompanyName");
        YOMI_FIRST_NAME = new UnindexedPropertyPath("persona:YomiFirstName");
        YOMI_LAST_NAME = new UnindexedPropertyPath("persona:YomiLastName");
        TITLE = new UnindexedPropertyPath("persona:Title");
        DEPARTMENT = new UnindexedPropertyPath("contacts:Department");
        COMPANY_NAME = new UnindexedPropertyPath("persona:CompanyName");
        EMAIL_ADDRESS = new UnindexedPropertyPath("persona:EmailAddress");
        EMAIL_ADDRESSES = new UnindexedPropertyPath("persona:EmailAddresses");
        PHONE_NUMBER = new UnindexedPropertyPath("persona:PhoneNumber");
        IM_ADDRESS = new UnindexedPropertyPath("persona:ImAddress");
        HOME_CITY = new UnindexedPropertyPath("persona:HomeCity");
        WORK_CITY = new UnindexedPropertyPath("persona:WorkCity");
        RELEVANCE_SCORE = new UnindexedPropertyPath("persona:RelevanceScore");
        FOLDER_IDS = new UnindexedPropertyPath("persona:FolderIds");
        ATTRIBUTIONS = new UnindexedPropertyPath("persona:Attributions");
        DISPLAY_NAMES = new UnindexedPropertyPath("persona:DisplayNames");
        FILE_ASES = new UnindexedPropertyPath("persona:FileAses");
        FILE_AS_IDS = new UnindexedPropertyPath("persona:FileAsIds");
        DISPLAY_NAME_PREFIXES = new UnindexedPropertyPath("persona:DisplayNamePrefixes");
        GIVEN_NAMES = new UnindexedPropertyPath("persona:GivenNames");
        MIDDLE_NAMES = new UnindexedPropertyPath("persona:MiddleNames");
        SURNAMES = new UnindexedPropertyPath("persona:Surnames");
        GENERATIONS = new UnindexedPropertyPath("persona:Generations");
        NICKNAMES = new UnindexedPropertyPath("persona:Nicknames");
        INITIALS = new UnindexedPropertyPath("persona:Initials");
        YOMI_COMPANY_NAMES = new UnindexedPropertyPath("persona:YomiCompanyNames");
        YOMI_FIRST_NAMES = new UnindexedPropertyPath("persona:YomiFirstNames");
        YOMI_LAST_NAMES = new UnindexedPropertyPath("persona:YomiLastNames");
        BUSINESS_PHONE_NUMBERS = new UnindexedPropertyPath("persona:BusinessPhoneNumbers");
        BUSINESS_PHONE_NUMBERS_2 = new UnindexedPropertyPath("persona:BusinessPhoneNumbers2");
        HOME_PHONES = new UnindexedPropertyPath("persona:HomePhones");
        HOME_PHONES_2 = new UnindexedPropertyPath("persona:HomePhones2");
        MOBILE_PHONES = new UnindexedPropertyPath("persona:MobilePhones");
        MOBILE_PHONES_2 = new UnindexedPropertyPath("persona:MobilePhones2");
        ASSISTANT_PHONE_NUMBERS = new UnindexedPropertyPath("persona:AssistantPhoneNumbers");
        CALLBACK_PHONES = new UnindexedPropertyPath("persona:CallbackPhones");
        CAR_PHONES = new UnindexedPropertyPath("persona:CarPhones");
        HOME_FAXES = new UnindexedPropertyPath("persona:HomeFaxes");
        ORGANIZATION_MAIN_PHONES = new UnindexedPropertyPath("persona:OrganizationMainPhones");
        OTHER_FAXES = new UnindexedPropertyPath("persona:OtherFaxes");
        OTHER_TELEPHONES = new UnindexedPropertyPath("persona:OtherTelephones");
        OTHER_PHONES_2 = new UnindexedPropertyPath("persona:OtherPhones2");
        PAGERS = new UnindexedPropertyPath("persona:Pagers");
        RADIO_PHONES = new UnindexedPropertyPath("persona:RadioPhones");
        TELEX_NUMBERS = new UnindexedPropertyPath("persona:TelexNumbers");
        WORK_FAXES = new UnindexedPropertyPath("persona:WorkFaxes");
        EMAILS_1 = new UnindexedPropertyPath("persona:Emails1");
        EMAILS_2 = new UnindexedPropertyPath("persona:Emails2");
        EMAILS_3 = new UnindexedPropertyPath("persona:Emails3");
        BUSINESS_HOME_PAGES = new UnindexedPropertyPath("persona:BusinessHomePages");
        PERSONAL_HOME_PAGES = new UnindexedPropertyPath("persona:PersonalHomePages");
        OFFICE_LOCATIONS = new UnindexedPropertyPath("persona:OfficeLocations");
        IM_ADDRESSES = new UnindexedPropertyPath("persona:ImAddresses");
        IM_ADDRESSES_2 = new UnindexedPropertyPath("persona:ImAddresses2");
        IM_ADDRESSES_3 = new UnindexedPropertyPath("persona:ImAddresses3");
        BUSINESS_ADDRESSES = new UnindexedPropertyPath("persona:BusinessAddresses");
        HOME_ADDRESSES = new UnindexedPropertyPath("persona:HomeAddresses");
        OTHER_ADDRESSES = new UnindexedPropertyPath("persona:OtherAddresses");
        TITLES = new UnindexedPropertyPath("persona:Titles");
        DEPARTMENTS = new UnindexedPropertyPath("persona:Departments");
        COMPANY_NAMES = new UnindexedPropertyPath("persona:CompanyNames");
        MANAGERS = new UnindexedPropertyPath("persona:Managers");
        ASSISTANT_NAMES = new UnindexedPropertyPath("persona:AssistantNames");
        PROFESSIONS = new UnindexedPropertyPath("persona:Professions");
        SPOUSE_NAMES = new UnindexedPropertyPath("persona:SpouseNames");
        CHILDREN = new UnindexedPropertyPath("persona:Children");
        SCHOOLS = new UnindexedPropertyPath("persona:School");
        HOBBIES = new UnindexedPropertyPath("persona:Hobbies");
        WEDDING_ANNIVERSARIES = new UnindexedPropertyPath("persona:WeddingAnniversaries");
        BIRTHDAYS = new UnindexedPropertyPath("persona:Birthdays");
        LOCATIONS = new UnindexedPropertyPath("persona:Locations");
        EXTENDED_PROPERTIES = new UnindexedPropertyPath("persona:ExtendedProperties");
    }
}
